### ISSUE TITLE
Unsupported operating system: centos

### ISSUE THREAD

**Issue by yao-big** [joeltgray/odooK8s#1]
![image](https://github.com/joeltgray/odooK8s/assets/30170943/f133a929-fa8c-42dc-804f-44f4230c49d5)

**Comment by SyntaxOutlaw** [comment]
Currently only Ubuntu and Arch are supported, if you want to commit changes to support CentOS feel free, but as I only use Arch and Ubuntu I won't be adding this support myself.

**Comment by SyntaxOutlaw** [comment]
Also the only thing that changes the support is a few packages that need to be installed, the issue arises because these distros use different package managers. I've tried to install as many packages with snap (even though I despise it) because it is distro agnostic once it's installed.

**Comment by SyntaxOutlaw** [comment]
Closing as works as intended
